project:
  type: book  
  output-dir: docs


book:
  page-navigation: true
  chapters:
    - intro.qmd
#    - summary.qmd
    - visualization.qmd
    - initial_modeling.qmd
    - diagnostics.qmd
    - add_noise.qmd
    - reg_cal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: kable
  pdf:
    documentclass: scrreprt

editor: visual

