project:
  type: book  
  output-dir: docs


book:
  page-navigation: true
  title: "Tutorial of Measurement Error Methods for Evaluating Blood Pressure using NHANES Data"
  author: "Avery Maytin, Anarina Murillo"
  date: "Last Updated February 2025"
  chapters:
#    - index.qmd
    - intro.qmd
#    - summary.qmd
    - visualization.qmd
    - initial_modeling.qmd
    - diagnostics.qmd
    - add_noise.qmd
    - reg_cal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: kable
  pdf:
    documentclass: scrreprt

editor: visual

